-- L03 PR Intent Layer — widen the existing (empty-on-purpose) `pr_intent`
-- scaffold table with the nine columns the derive/read/cache flow needs.
--
-- HAND-ADDED CHECK: the trailing `ALTER TABLE ... ADD CONSTRAINT` below was
-- added BY HAND, not generated by drizzle-kit. `text('confidence', { enum:
-- [...] })` in db/schema/reviews.ts is TYPES-ONLY — it narrows the Drizzle/TS
-- type but emits no CHECK constraint — so the DB-level guarantee has to be
-- appended manually. Consequence, stated so nobody "fixes" it later:
-- drizzle-kit's snapshot (meta/0013_snapshot.json) has no record of this
-- constraint, so a future `drizzle-kit generate` will not see it as
-- pre-existing and will not emit a DROP for it either — it is simply
-- invisible to the tool, not fought by it. Confidence is business-logic-
-- driven and expected to gain/lose values over time, which is why it's
-- TEXT + CHECK rather than a Postgres ENUM (adding/removing an ENUM value
-- needs its own migration and a value can never be dropped).
--
-- `workspace_id` IS DELIBERATELY ABSENT from this table. `pr_intent` is not
-- a domain table under server/AGENTS.md's "every domain table carries
-- workspace_id" invariant — it is a SATELLITE keyed 1:1 on `pull_requests.id`
-- by a primary key that is ALSO a cascading FK (`prId` above), exactly like
-- `findings`, `pr_files`, `pr_commits` and `pr_brief`. It is unreachable
-- except through a parent row that already carries `workspace_id`, and
-- duplicating that column here would be a denormalization no constraint can
-- keep in sync — it would drift silently while giving a false sense of a
-- DB-enforced tenancy boundary. The boundary is enforced ONE LAYER UP
-- instead, where it is actually reviewable: every `pr_intent` entry point
-- resolves `workspaceId` via `getContext`, then loads the parent row through
-- the already-scoped `getPull(workspaceId, prId)`
-- (modules/reviews/repository/pull.repo.ts), throwing `NotFoundError` before
-- any `pr_intent` statement runs. See the docblock above `getIntentRow` /
-- `upsertIntent` in that file for the same reasoning, kept where the next
-- person editing the query will actually look.
--
-- NO INDEXES added. Every access path here is `WHERE pr_id = $1`, and
-- `pr_id` is the PRIMARY KEY — already a B-tree index, which also satisfies
-- the "FK columns need an index" rule since `pr_id` is itself the FK to
-- `pull_requests.id`. Do not add a decorative one.
ALTER TABLE "pr_intent" ADD COLUMN "confidence" text DEFAULT 'low' NOT NULL;--> statement-breakpoint
ALTER TABLE "pr_intent" ADD COLUMN "sources" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "pr_intent" ADD COLUMN "derived_from_sha" text NOT NULL;--> statement-breakpoint
ALTER TABLE "pr_intent" ADD COLUMN "derived_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "pr_intent" ADD COLUMN "provider" text;--> statement-breakpoint
ALTER TABLE "pr_intent" ADD COLUMN "model" text;--> statement-breakpoint
ALTER TABLE "pr_intent" ADD COLUMN "tokens_in" integer;--> statement-breakpoint
ALTER TABLE "pr_intent" ADD COLUMN "tokens_out" integer;--> statement-breakpoint
ALTER TABLE "pr_intent" ADD COLUMN "cost_usd" double precision;--> statement-breakpoint
ALTER TABLE "pr_intent" ADD CONSTRAINT "pr_intent_confidence_check" CHECK ("confidence" IN ('high', 'medium', 'low'));