import type { CSSProperties } from "react";

/** Co-located styles for ImportSkillDrawer. */
export const s = {
  section: { marginBottom: 20 } satisfies CSSProperties,
  divider: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    margin: "18px 0",
    color: "var(--text-muted)",
    fontSize: 12,
  } satisfies CSSProperties,
  dividerLine: { flex: 1, height: 1, background: "var(--border)" } satisfies CSSProperties,
  dropzone: {
    border: "1px dashed var(--border-strong)",
    borderRadius: 8,
    padding: "18px 14px",
    textAlign: "center",
    color: "var(--text-secondary)",
    fontSize: 13,
    cursor: "pointer",
    marginBottom: 16,
  } satisfies CSSProperties,
  previewHeading: { fontSize: 15, fontWeight: 700, marginBottom: 4 } satisfies CSSProperties,
  previewMeta: { display: "flex", alignItems: "center", gap: 8, marginBottom: 12 } satisfies CSSProperties,
  previewDescription: { fontSize: 13, color: "var(--text-secondary)", marginBottom: 14 } satisfies CSSProperties,
  bodyCard: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: 14,
    background: "var(--bg-elevated)",
    marginBottom: 16,
    maxHeight: 320,
    overflow: "auto",
  } satisfies CSSProperties,
  notice: {
    display: "flex",
    gap: 10,
    padding: 12,
    borderRadius: 8,
    background: "var(--warn-bg)",
    color: "var(--warn)",
    fontSize: 13,
    lineHeight: 1.5,
    marginBottom: 16,
  } satisfies CSSProperties,
  warningsBox: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  warningsTitle: { fontWeight: 600, marginBottom: 6, color: "var(--text-primary)" } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  confirmHint: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
