/* GraphView — the same blast radius as a node-link diagram. Deliberately thin:
   the source is generated by the pure `buildFlowchart`, and `MermaidDiagram`
   only renders it. `MermaidDiagram` renders `null` for anything mermaid.parse
   rejects, so a malformed source is a blank area with no error — which is why
   the assertions are on the generated string, not on the render (R16). */
"use client";

import React from "react";
import { useTranslations } from "next-intl";
import { MermaidDiagram } from "@/components/mermaid-diagram/MermaidDiagram";
import type { PrBlastRadius } from "@/lib/types";
import { buildFlowchart } from "./helpers";
import { s } from "./styles";

export function GraphView({
  data,
  repoFullName,
  sha,
}: {
  data: PrBlastRadius;
  repoFullName: string | null;
  /** The sha every `click … href` is pinned to — `indexed_sha`, never head. */
  sha: string;
}) {
  const t = useTranslations("blast");
  const chart = buildFlowchart(data, repoFullName, sha);

  if (!chart) return <p style={s.note}>{t("graph.empty")}</p>;

  return (
    <div role="img" aria-label={t("graph.ariaLabel")}>
      <MermaidDiagram chart={chart} />
    </div>
  );
}
