import type { CSSProperties } from "react";

export const s = {
  card: {
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderWidth: 1,
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  badgeRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  summary: {
    fontSize: 13.5,
    lineHeight: 1.6,
    color: "var(--text-secondary)",
    margin: 0,
  } satisfies CSSProperties,
  statRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  } satisfies CSSProperties,
  note: {
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--text-muted)",
    margin: 0,
  } satisfies CSSProperties,
  explanation: {
    fontSize: 13.5,
    lineHeight: 1.6,
    color: "var(--text-secondary)",
    margin: 0,
    borderLeftStyle: "solid",
    borderLeftColor: "var(--accent)",
    borderLeftWidth: 2,
    paddingLeft: 10,
  } satisfies CSSProperties,
  /* --- tree --- */
  tree: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  symbolRow: {
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderWidth: 1,
    borderRadius: 6,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  symbolHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "8px 10px",
    background: "none",
    borderStyle: "none",
    borderWidth: 0,
    cursor: "pointer",
    textAlign: "left",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  symbolName: {
    fontSize: 13,
    fontWeight: 600,
  } satisfies CSSProperties,
  symbolMeta: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  symbolBody: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: "0 10px 10px 26px",
  } satisfies CSSProperties,
  listLabel: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  list: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  listItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    lineHeight: 1.55,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  chipRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  } satisfies CSSProperties,
  /* --- reverse impact --- */
  reverseGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    marginTop: 4,
  } satisfies CSSProperties,
  spacer: {
    flex: "1 1 auto",
  } satisfies CSSProperties,
} as const;
